# Generated by Django 4.2.9 on 2024-01-17 18:05

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('photo_conversion', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProjectConversion',
            new_name='PhotoConversion',
        ),
    ]
