# Generated by Django 4.2.9 on 2024-03-09 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo_conversion', '0004_photoconversion_loss'),
    ]

    operations = [
        migrations.AddField(
            model_name='photoconversion',
            name='resolution',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
