# Generated by Django 4.2.19 on 2025-02-28 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo_conversion', '0005_photoconversion_resolution'),
    ]

    operations = [
        migrations.AddField(
            model_name='photoconversion',
            name='enhanced_image',
            field=models.ImageField(blank=True, null=True, upload_to='enhanced_images/'),
        ),
    ]
